-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 16:31:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vaccine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vaccine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaccine` DEFAULT CHARACTER SET utf8 ;
USE `vaccine` ;

-- -----------------------------------------------------
-- Table `vaccine`.`vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccine`.`vaccine` (
  `id_vaccine` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `shots_amount` TINYINT NOT NULL AUTO_INCREMENT,
  `revactination_time` TIMESTAMP NULL,
  PRIMARY KEY (`id_vaccine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaccine`.`child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccine`.`child` (
  `id_child` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `birthDate` DATE NOT NULL,
  PRIMARY KEY (`id_child`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaccine`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccine`.`hospital` (
  `id_hospital` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `telephone` VARCHAR(50) NULL,
  PRIMARY KEY (`id_hospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaccine`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccine`.`doctor` (
  `id_doctor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `id_hospital` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_doctor`, `id_hospital`),
  INDEX `fk_doctor_hospital1_idx` (`id_hospital` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_hospital1`
    FOREIGN KEY (`id_hospital`)
    REFERENCES `vaccine`.`hospital` (`id_hospital`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vaccine`.`vaccine_done`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccine`.`vaccine_done` (
  `date` INT NOT NULL,
  `id_vaccine` INT NOT NULL,
  `id_child` INT UNSIGNED NOT NULL,
  `id_doctor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_vaccine`, `id_child`, `id_doctor`, `date`),
  INDEX `fk_vaccine_done_child1_idx` (`id_child` ASC) VISIBLE,
  INDEX `fk_vaccine_done_doctor1_idx` (`id_doctor` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_done_vaccine2`
    FOREIGN KEY (`id_vaccine`)
    REFERENCES `vaccine`.`vaccine` (`id_vaccine`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vaccine_done_child1`
    FOREIGN KEY (`id_child`)
    REFERENCES `vaccine`.`child` (`id_child`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vaccine_done_doctor1`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `vaccine`.`doctor` (`id_doctor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
