-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 10:16:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab3_14
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab3_14
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab3_14` DEFAULT CHARACTER SET utf8 ;
USE `lab3_14` ;

-- -----------------------------------------------------
-- Table `lab3_14`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab3_14`.`university` (
  `id_university` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_university`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab3_14`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab3_14`.`student` (
  `id_student` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `group` VARCHAR(45) NOT NULL,
  `id_university` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_student`, `id_university`),
  INDEX `fk_student_university1_idx` (`id_university` ASC) VISIBLE,
  CONSTRAINT `fk_student_university1`
    FOREIGN KEY (`id_university`)
    REFERENCES `lab3_14`.`university` (`id_university`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab3_14`.`p_e_standart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab3_14`.`p_e_standart` (
  `id_p_e_standart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `average_result` VARCHAR(45) NOT NULL,
  `record_result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_p_e_standart`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab3_14`.`p_e_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab3_14`.`p_e_teacher` (
  `id_p_e_teacher` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `university_id_university` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_p_e_teacher`, `university_id_university`),
  INDEX `fk_p_e_teacher_university1_idx` (`university_id_university` ASC) VISIBLE,
  CONSTRAINT `fk_p_e_teacher_university1`
    FOREIGN KEY (`university_id_university`)
    REFERENCES `lab3_14`.`university` (`id_university`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab3_14`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab3_14`.`result` (
  `id_p_e_standart` INT UNSIGNED NOT NULL,
  `id_student` INT UNSIGNED NOT NULL,
  `id_p_e_teacher` INT UNSIGNED NOT NULL,
  `grade` TINYINT(5) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_p_e_standart`, `id_student`, `id_p_e_teacher`),
  INDEX `fk_result_p_e_standart1_idx` (`id_p_e_standart` ASC) VISIBLE,
  INDEX `fk_result_student1_idx` (`id_student` ASC) VISIBLE,
  INDEX `fk_result_p_e_teacher1_idx` (`id_p_e_teacher` ASC) VISIBLE,
  CONSTRAINT `fk_result_p_e_standart1`
    FOREIGN KEY (`id_p_e_standart`)
    REFERENCES `lab3_14`.`p_e_standart` (`id_p_e_standart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_student1`
    FOREIGN KEY (`id_student`)
    REFERENCES `lab3_14`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_p_e_teacher1`
    FOREIGN KEY (`id_p_e_teacher`)
    REFERENCES `lab3_14`.`p_e_teacher` (`id_p_e_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
